# Generated by Django 3.0 on 2019-12-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comment', '0002_auto_20191207_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=256, verbose_name='内容'),
        ),
    ]
