# Generated by Django 3.0 on 2019-12-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_post_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=False, verbose_name='Markdown语法'),
        ),
    ]
